
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import filedialog as fd

import numpy as np
import shutil as sh
from PIL import Image, ImageTk
from image_processing import train_images, test_image

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def select_dir():
    filepath = fd.askdirectory(
        initialdir="../",
        title='Choose directory'
    )

    if (len(filepath) != 0):
        pict_path, mean_face, EigFace, Om = train_images(filepath)
        np.savetxt("data/pict_path.txt", pict_path, fmt="%s")
        np.savetxt("data/mean_face.txt", mean_face)
        np.savetxt("data/EigFace.txt", EigFace)
        np.savetxt("data/Om.txt", Om)

def select_file():
    pict_path = np.genfromtxt("data/pict_path.txt", dtype="str", delimiter="\n")
    mean_face = np.loadtxt("data/mean_face.txt")
    EigFace = np.loadtxt("data/EigFace.txt")
    Om = np.loadtxt("data/Om.txt")
    if (len(mean_face) != 0):
        filetypes = ( 
            ("Image files", "*.png"),
            ("Image files", "*.jpg"),
            ("All files", "*.*")
        )

        filename = fd.askopenfilename(
            initialdir='../',
            title='Choose file',
            filetypes=filetypes
        )

        if (len(filename) != 0):
            img = Image.open(filename).resize((256,256))
            img = ImageTk.PhotoImage(img)
            canvas.itemconfigure(image_2, image=img)
            # image_2.configure(image=img)
            # img = PhotoImage(file=filename)
            # canvas.itemconfig(image_2, image=img)

            output = test_image(filename, pict_path, mean_face, EigFace, Om)

            print(output)

            img = Image.open(output).resize((256,256), Image.BICUBIC)
            img = ImageTk.PhotoImage(img)
            canvas.itemconfig(image_3, image=img)

    else:
        print("Silahkan lakukan training terlebih dahulu!")



window = Tk()

window.title("Image Recognition")
window.geometry("960x540")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 540,
    width = 960,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
canvas.pack()

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    480.0,
    270.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=select_file,
    relief="flat"
)
button_1.place(
    x=66.0,
    y=448.0,
    width=140.0,
    height=32.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=select_dir,
    relief="flat"
)
button_2.place(
    x=308.0,
    y=446.0,
    width=140.0,
    height=32.0
)

canvas.create_text(
    301.0,
    412.0,
    anchor="nw",
    text="Insert Your Dataset",
    fill="#FFFFFF",
    font=("K2D Light", 18 * -1)
)

canvas.create_text(
    52.0,
    412.0,
    anchor="nw",
    text="Insert Your Image\n",
    fill="#FFFFFF",
    font=("K2D Light", 18 * -1)
)

canvas.create_text(
    581.0,
    412.0,
    anchor="nw",
    text="Result",
    fill="#FFFFFF",
    font=("K2D Light", 18 * -1)
)

canvas.create_text(
    777.0,
    412.0,
    anchor="nw",
    text="Excecution Time",
    fill="#FFFFFF",
    font=("K2D Light", 18 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    250.0,
    229.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    715.0,
    229.0,
    image=image_image_3
)

canvas.create_text(
    322.0,
    12.0,
    anchor="nw",
    text="FACE RECOGNITION",
    fill="#FFFFFF",
    font=("Kadwa Regular", 32 * -1)
)

canvas.create_rectangle(
    34.0,
    73.0,
    922.0,
    76.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    202.0,
    357.0,
    anchor="nw",
    text="Test Image",
    fill="#FFFFFF",
    font=("Kadwa Regular", 18 * -1)
)

canvas.create_text(
    655.0,
    357.0,
    anchor="nw",
    text="Closest Result",
    fill="#FFFFFF",
    font=("Kadwa Regular", 18 * -1)
)
window.resizable(False, False)
window.mainloop()